<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use App\Favorite;

class Workstation extends Model
{

    protected $with = ['location'];

    public function location()
    {
        return $this->belongsTo('App\Models\Location');
    }
    public function favorite()
    {
        return $this->belongsTo('App\Models\Favorite');
    }
    public function toArray()
    {
        $parent =  parent::toArray(); // TODO: Change the autogenerated stub

        if ( Auth::check() ){
            $parent['isFavorite'] = true  ;
        }

        return $parent ;
    }
    private function isFavorite(){

    }



}
